import Header from "./Header";
import Footer from "./Footer";
import ContactInfo from "./ContactInfo";
import Head from "next/head";
import { css } from "@emotion/react";

type Props = {
  children: React.ReactNode;
  showContactInfo?: boolean;
};

const Layout = ({ children, showContactInfo = true }: Props) => {
  return (
    <>
      <Head>
        <title>国際バイタルディバイス</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex"></meta>
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width,initial-scale=1.0,maximum-scale=1.0"
        />
      </Head>
      <div css={wrapper}>
        <Header />
        <main>
          {children}
          {showContactInfo && <ContactInfo />}
        </main>
        <Footer />
      </div>
    </>
  );
};

// モバイルメニュー表示時のoverlayのため
const wrapper = css`
  position: relative;
`;

export default Layout;