import Header from "@components/layout/Header";
import ContactInfo from "@components/layout/ContactInfo";
import Footer from "@components/layout/Footer";
import Head from "next/head";
import type { ReactElement } from "react";
import Faq from "@components/views/faq/Faq";
import type { NextPageWithLayout } from "./_app";
import { css } from "@emotion/react";

const FaqPage: NextPageWithLayout = () => {
  return <Faq />;
};

FaqPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <Head>
        <title>国際バイタルディバイス</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div css={wrapper}>
        <Header />
        <main>
          {page}
          <ContactInfo />
        </main>
        <Footer />
      </div>
    </>
  );
};

// メニュー表示時のoverlayのため
const wrapper = css`
  position: relative;
`;

export default FaqPage;
