import Header from "@components/layout/Header";
import HeroSection from "@components/views/home/HeroSection";
import ProductSection from "@components/views/home/ProductSection";
import VideoSection from "@components/views/home/VideoSection";
import ContactInfo from "@components/layout/ContactInfo";
import Footer from "@components/layout/Footer";
import Head from "next/head";
import { css } from "@emotion/react";
import { ReactElement, useEffect } from "react";
import type { NextPageWithLayout } from "./_app";
import ServiceSection from "@components/views/home/ServiceSection";

const HomePage: NextPageWithLayout = () => {
  useFillViewportHeight();

  return (
    <>
      <HeroSection />
      <ServiceSection />
      <ProductSection />
      <VideoSection />
    </>
  );
};

HomePage.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <Head>
        <title>国際バイタルディバイス</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div css={wrapper}>
        <Header />
        <main>
          {page}
          <ContactInfo />
        </main>
        <Footer />
      </div>
    </>
  );
};
const useFillViewportHeight = () => {
  useEffect(() => {
    const setViewportHeight = () => {
      const vh = window.innerHeight * 0.01;
      document.documentElement.style.setProperty("--vh", `${vh}px`);
    };

    // 画面の横幅にサイズ変動がある場合、高さを再取得
    let viewWidth = window.innerWidth;
    window.addEventListener("resize", () => {
      if (viewWidth === window.innerWidth) {
        return;
      }
      viewWidth = window.innerWidth;
      setViewportHeight();
    });
    setViewportHeight();
    console.log("画面リサイズ");
  }, []);
};

const wrapper = css`
  position: relative;
`;

export default HomePage;
