import Header from "../components/common/Header";
import ContactInfo from "../components/common/ContactInfo";
import Footer from "../components/common/Footer";
import Head from "next/head";
import { css } from "@emotion/react";
import { mqLarge } from "../utils/style";
import type { ReactElement } from "react";

import type { NextPageWithLayout } from "./_app";

const Company: NextPageWithLayout = () => {
  return (
    <>
      <div css={wrapperInner}>
        <div css={title}>
          <h1>会社情報</h1>
          <p>Company</p>
        </div>
        <div css={container}></div>
      </div>
    </>
  );
};

Company.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <Head>
        <title>国際バイタルディバイス</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div css={wrapper}>
        <Header />
        <main>
          {page}
          <ContactInfo />
        </main>
        <Footer />
      </div>
    </>
  );
};

const wrapper = css`
  position: relative;
`;
const wrapperInner = css`
  background-color: whitesmoke;
  padding-top: 11rem;
  height: 1400px;
  ${mqLarge} {
    position: relative;
  }
`;
const container = css`
  ${mqLarge} {
    position: absolute;
    top: 24rem;
    /* left: 0; */
    height: 800px;
    width: 1700px;
    max-width: 1700px;
    background-color: white;
    box-shadow: 6px 6px 20px gainsboro;
  }
`;
const title = css`
  max-width: 1200px;
  margin-left: 3rem;
  p {
    font-size: 1rem;
  }
  ${mqLarge} {
    margin: 0 auto;
    h1 {
      /* font-size: 2.7rem; */
    }
    p {
      color: black;
      font-size: 1.2rem;
      text-align: left;
    }
  }
`;

export default Company;
