import Header from "../components/common/Header";
import Footer from "../components/common/Footer";
import Head from "next/head";
import type { ReactElement } from "react";
import Contact from "../components/pages/contact/Contact";
import type { NextPageWithLayout } from "./_app";
import { css } from "@emotion/react";

const ContactPage: NextPageWithLayout = () => {
  return <Contact />;
};

ContactPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <Head>
        <title>国際バイタルディバイス</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex"></meta>
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width,initial-scale=1.0,maximum-scale=1.0"
        ></meta>
      </Head>
      <div css={wrapper}>
        <Header />
        <main>{page}</main>
        <Footer />
      </div>
    </>
  );
};

export default ContactPage;

// メニュー表示時のoverlayのため
const wrapper = css`
  position: relative;
`;
