import Header from "../components/common/Header";
import ContactInfo from "../components/common/ContactInfo";
import Footer from "../components/common/Footer";
import Head from "next/head";
import type { ReactElement } from "react";
import Contact from "../components/contact/Contact";

import type { NextPageWithLayout } from "./_app";

const ContactPage: NextPageWithLayout = () => {
  return <Contact />;
};

ContactPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <Head>
        <title>国際バイタルディバイス</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <main>
          {page}
          <ContactInfo />
        </main>
        <Footer />
      </div>
    </>
  );
};

export default ContactPage;
