import Header from "../components/common/Header";
import ContactInfo from "../components/common/ContactInfo";
import Footer from "../components/common/Footer";
import Head from "next/head";
import type { ReactElement } from "react";
import Faq from "../components/faq/Faq";

import type { NextPageWithLayout } from "./_app";
import { css } from "@emotion/react";
import { motion } from "framer-motion";

const FaqPage: NextPageWithLayout = () => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: 10 }}
      transition={{ duration: 0.3 }}
    >
      <Faq />
    </motion.div>
  );
};

FaqPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <Head>
        <title>国際バイタルディバイス</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div css={wrapper}>
        <Header />
        <main>
          {page}
          <ContactInfo />
        </main>
        <Footer />
      </div>
    </>
  );
};

// メニュー表示時のoverlayのため
const wrapper = css`
  position: relative;
`;

export default FaqPage;
