import Header from "../components/common/Header";
import Hero from "../components/pages/home/Hero";
import ProductSection from "../components/pages/home/ProductSection";
import VideoSection from "../components/pages/home/VideoSection";
import ContactInfo from "../components/common/ContactInfo";
import Footer from "../components/common/Footer";
import Head from "next/head";
import { setViewportHeight } from "../utils/SetViewportHeight";
import { css } from "@emotion/react";
import type { ReactElement } from "react";
import type { NextPageWithLayout } from "./_app";
import ServiceSection from "../components/pages/home/ServiceSection";

const HomePage: NextPageWithLayout = () => {
  setViewportHeight();

  return (
    <>
      <Hero />
      <ServiceSection />
      <ProductSection />
      <VideoSection />
    </>
  );
};

HomePage.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <Head>
        <title>国際バイタルディバイス</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div css={wrapper}>
        <Header />
        <main>
          {page}
          <ContactInfo />
        </main>
        <Footer />
      </div>
    </>
  );
};

const wrapper = css`
  position: relative;
`;

export default HomePage;
