import Header from "../components/common/Header";
import Hero from "../components/home/Hero";
import Service from "../components/home/Service";
import Product from "../components/home/Product";
import Video from "../components/home/Video";
import ContactInfo from "../components/common/ContactInfo";
import Footer from "../components/common/Footer";
import Head from "next/head";
import { SetFillHeight, useScrolledYZero } from "../utils/style";
import { css } from "@emotion/react";
import { mqLarge } from "../utils/style";
import type { ReactElement } from "react";
import type { NextPageWithLayout } from "./_app";

const Home: NextPageWithLayout = () => {
  // SetFillHeight();

  return (
    <>
      <Hero />
      <Service />
      <Product />
      <Video />
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  const isHomeAndTop: boolean = useScrolledYZero();
  return (
    <>
      <Head>
        <title>国際バイタルディバイス</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div css={wrapper}>
        <Header isHomeAndTop={isHomeAndTop} />
        <main>
          {page}
          <ContactInfo />
        </main>
        <Footer />
      </div>
    </>
  );
};

const wrapper = css`
  position: relative;
`;

export default Home;
