import Header from "../layouts/common/Header";
import Hero from "../layouts/home/Hero";
import Service from "../layouts/home/Service";
import Product from "../layouts/home/Product";
import Video from "../layouts/home/Video";
import Contact from "../layouts/common/Contact";
import Footer from "../layouts/common/Footer";
import Head from "next/head";
import SetFillHeight from "../components/styles";
import { css } from "@emotion/react";
import type { NextPage } from "next";

// return <>{isWide ? <DesktopIndex /> : <MobileIndex />}</>;

const Home: NextPage = () => {
  SetFillHeight();

  return (
    <>
      <Head>
        <title>国際バイタルディバイス</title>
        <meta name="description" content="Generated by create next app" />
        {/* <meta
          name="google-site-verification"
          content="kY6fiMWfihtF4fXQ2yO868cgLRZxQp1g8nLORUkGSnQ"
        /> */}
        <meta name="robots" content="noindex"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div css={wrap}>
        <Header />
        <main>
          <Hero />
          <Service />
          <Product />
          <Video />
          <Contact />
        </main>
        <Footer />
      </div>
    </>
  );
};

const wrap = css`
  position: relative;
`;

export default Home;
